Resources:
  MyFirstLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "MyFirstLambdaFunction"
      Handler: "index.handler" # Update with your handler information
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: "nodejs14.x" # Update with your runtime
      Code:
        S3Bucket: "your-s3-bucket-name"
        S3Key: "your-s3-key-for-lambda1.zip"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        # IAM role policy
