FROM public.ecr.aws/lambda/python:3.11


ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_DEFAULT_REGION
ARG MY_EMAIL_ADDRESS
ARG OPENAI_API_KEY
ARG NEWS_API_KEY
ARG RAPID_API_KEY

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION ${AWS_DEFAULT_REGION}
ENV MY_EMAIL_ADDRESS ${MY_EMAIL_ADDRESS}
ENV OPENAI_API_KEY ${OPENAI_API_KEY}
ENV NEWS_API_KEY ${NEWS_API_KEY}
ENV RAPID_API_KEY ${RAPID_API_KEY}

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt

COPY main.py ${LAMBDA_TASK_ROOT}
COPY datasource ${LAMBDA_TASK_ROOT}/datasource
COPY clients ${LAMBDA_TASK_ROOT}/clients

ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}"
ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}/clients"
ENV PYTHONPATH "${PYTHONPATH}:${LAMBDA_TASK_ROOT}/datasource"

CMD [ "main.handler" ]
