AWSTemplateFormatVersion: '2010-09-09'
Description: Robonews Root Stack

Parameters:
  BucketName:
    Type: String
    Description: Name of the Robonews bucket
  SenderLambdaName:
    Type: String
    Description: Name of the sender lambda
  SenderLambdaImageUri:
    Type: String
    Description: Uri of the sender lambda image
  SenderTemplateUrl:
    Type: String
    Description: Url of the sender stack template
  SubscribeLambdaName:
    Type: String
    Description: Name of the subscribe lambda
  UnsubscribeLambdaName:
    Type: String
    Description: Name of the unsubscribe lambda
  SubscriptionTemplateUrl:
    Type: String
    Description: Url of the subscription template

Resources:
  SubscriptionStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "http://s3.amazonaws.com/${SubscriptionTemplateUrl}"
      Parameters:
        BucketName: !Ref BucketName
        SubscribeLambdaName: !Ref SubscribeLambdaName
        UnsubscribeLambdaName: !Ref UnsubscribeLambdaName

  SenderStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: SubscriptionStack
    Properties:
      TemplateURL: !Sub "http://s3.amazonaws.com/${SenderTemplateUrl}"
      Parameters:
        LambdaFunctionName: !Ref SenderLambdaName
        ImageUri: !Ref SenderLambdaImageUri


