AWSTemplateFormatVersion: '2010-09-09'
Description: Robonews Root Stack

Parameters:
  BucketName:
    Type: String
    Description: Name of the Robonews bucket
  SenderLambdaName:
    Type: String
    Description: Name of the sender lambda
  SenderLambdaImageUri:
    Type: String
    Description: Uri of the sender lambda image
  SenderTemplateUrl:
    Type: String
    Description: Url of the sender stack template
  ConfirmLambdaName:
    Type: String
    Description: Name of the confirmation lambda
  SubscribeLambdaName:
    Type: String
    Description: Name of the subscribe lambda
  UnsubscribeLambdaName:
    Type: String
    Description: Name of the unsubscribe lambda
  SubscriptionTemplateUrl:
    Type: String
    Description: Url of the subscription template
  Tag:
    Type: String
    Description: Randomly generated unique tag
  MailgunApiKey:
    Type: String
    Description: API key for mailgun email service

Resources:
  SymmetricKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Symmetric encryption key for Robonews app
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowRootAccountAdministration
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - 'kms:*'
            Resource: '*'
          - Sid: AllowAllKeyAccess
            Effect: Allow
            Principal: '*'
            Action: 'kms:*'
            Resource: '*'

  SubscriptionStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Sub "http://s3.amazonaws.com/${SubscriptionTemplateUrl}"
      Parameters:
        BucketName: !Ref BucketName
        ConfirmLambdaName: !Ref ConfirmLambdaName
        SubscribeLambdaName: !Ref SubscribeLambdaName
        UnsubscribeLambdaName: !Ref UnsubscribeLambdaName
        EncryptionKeyId: !Ref SymmetricKey
        Tag: !Ref Tag
        MailgunApiKey: !Ref MailgunApiKey

  SenderStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: SubscriptionStack
    Properties:
      TemplateURL: !Sub "http://s3.amazonaws.com/${SenderTemplateUrl}"
      Parameters:
        LambdaFunctionName: !Ref SenderLambdaName
        ImageUri: !Ref SenderLambdaImageUri
        EncryptionKeyId: !Ref SymmetricKey
        MailgunApiKey: !Ref MailgunApiKey


