AWSTemplateFormatVersion: '2010-09-09'
Resources:
  UserEmailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserEmails
      AttributeDefinitions:
        - AttributeName: Email
          AttributeType: S
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Email
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
